import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {

  const submit = async (e) => {
    e.preventDefault()
    const formData = {
      name: e.target.name.value,
      note: e.target.note.value
    }

    fetch('/api/notes', {
      method: 'POST',
      body: JSON.stringify(formData)
    })

    console.table(formData)
  }
  
  return (
    <>
      <Head>
        <title>API REST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>API REST</h1>
        <form action="/api/hello" method="POST" onSubmit={submit}>
          <input placeholder='name' type="text" name="name" />
          <input placeholder='note' type="text" name="note" />
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}
